name: Build macOS Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --clean --onefile --name pdftojson pdftojson
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdftojson-macos
        path: dist/pdftojson