name: Build macOS Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        brew install tesseract poppler
        python -m pip install --upgrade pip
        pip install pdfplumber pytesseract pdf2image nltk Pillow pyinstaller
        python -c "import nltk; nltk.download('punkt')"
    
    - name: Build executable
      run: |
        pyinstaller --clean --onefile --name pdftojson \
          --add-data "/usr/local/bin/tesseract:." \
          --add-data "/usr/local/lib/libtesseract.dylib:." \
          --add-data "$(python -c 'import nltk; print(nltk.data.path[0])')/tokenizers/punkt:nltk_data/tokenizers/punkt" \
          pdftojson
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdftojson-macos
        path: dist/pdftojson